spring.application.name=expanse-tracker-app
<<<<<<< HEAD
=======

spring.datasource.url=jdbc:mysql://mysql-db:3306/expense_tracker_app
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt-secret=mysupersecretkeymysupersecretkey123456
app.jwt-expiration-milliseconds=86400000
>>>>>>> 7399c94 (backend ready)
