spring.application.name=expense-tracker-app

server.port=${PORT:8080}

# HARDCODE the full JDBC URL directly:
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mdCnChHRxlLNZtXwMFMEeObsYrqZxALR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT - also hardcoded:
app.jwt-secret=mysupersecretkeymysupersecretkey123456
app.jwt-expiration-milliseconds=86400000