spring.application.name=expense-tracker-app

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt-secret=${JWT_SECRET}
app.jwt-expiration-milliseconds=${JWT_EXPIRATION}